author = "Oliver Paisley"
baseurl = "https://oliverpaisley.com"
canonifyurls = true
paginate = 3
theme = "hugo-alageek-theme"
title = "Oliver Paisley"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
copyright = "© 2018 by Oliver Paisley"
copyrightUrl = "https://oliverpaisley.com"
faviconfile = "img/jester-white.png"
# latestpostcount = 5
logofile = "img/jester-white.png"
highlightjs = true


description = "A personal website for Oliver Paisley."

twitter = "oliverjdpaisley"
linkedin = "oliverpaisley"
github = "oliverpaisley"
instagram = "oliverjdpaisley"
progressively = true


[[menu.primary]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20